from pydantic import BaseModel, Field
from typing import Optional

class Food(BaseModel):
    category: str = Field(..., alias="Category")
    description: str = Field(..., alias="Description")
    nutrient_data_bank_number: str = Field(..., alias="Nutrient Data Bank Number")
    data_alpha_carotene: Optional[float] = Field(None, alias="Data.Alpha Carotene")
    data_ash: Optional[float] = Field(None, alias="Data.Ash")
    data_beta_carotene: Optional[float] = Field(None, alias="Data.Beta Carotene")
    data_beta_cryptoxanthin: Optional[float] = Field(None, alias="Data.Beta Cryptoxanthin")
    data_carbohydrate: Optional[float] = Field(None, alias="Data.Carbohydrate")
    data_cholesterol: Optional[float] = Field(None, alias="Data.Cholesterol")
    data_choline: Optional[float] = Field(None, alias="Data.Choline")
    data_fiber: Optional[float] = Field(None, alias="Data.Fiber")
    data_kilocalories: Optional[float] = Field(None, alias="Data.Kilocalories")
    data_lutein_and_zeaxanthin: Optional[float] = Field(None, alias="Data.Lutein and Zeaxanthin")
    data_lycopene: Optional[float] = Field(None, alias="Data.Lycopene")
    data_manganese: Optional[float] = Field(None, alias="Data.Manganese")
    data_niacin: Optional[float] = Field(None, alias="Data.Niacin")
    data_pantothenic_acid: Optional[float] = Field(None, alias="Data.Pantothenic Acid")
    data_protein: Optional[float] = Field(None, alias="Data.Protein")
    data_refuse_percentage: Optional[float] = Field(None, alias="Data.Refuse Percentage")
    data_retinol: Optional[float] = Field(None, alias="Data.Retinol")
    data_riboflavin: Optional[float] = Field(None, alias="Data.Riboflavin")
    data_selenium: Optional[float] = Field(None, alias="Data.Selenium")
    data_sugar_total: Optional[float] = Field(None, alias="Data.Sugar Total")
    data_thiamin: Optional[float] = Field(None, alias="Data.Thiamin")
    data_water: Optional[float] = Field(None, alias="Data.Water")
    data_fat_monosaturated_fat: Optional[float] = Field(None, alias="Data.Fat.Monosaturated Fat")
    data_fat_polysaturated_fat: Optional[float] = Field(None, alias="Data.Fat.Polysaturated Fat")
    data_fat_saturated_fat: Optional[float] = Field(None, alias="Data.Fat.Saturated Fat")
    data_fat_total_lipid: Optional[float] = Field(None, alias="Data.Fat.Total Lipid")
    data_household_weights_gram: Optional[float] = Field(None, alias="Data.Household Weights(Gram)")
    data_household_weight_description: Optional[str] = Field(None, alias="Data.Household Weight Description")
    data_major_minerals_calcium: Optional[float] = Field(None, alias="Data.Major Minerals.Calcium")
    data_major_minerals_copper: Optional[float] = Field(None, alias="Data.Major Minerals.Copper")
    data_major_minerals_iron: Optional[float] = Field(None, alias="Data.Major Minerals.Iron")
    data_major_minerals_magnesium: Optional[float] = Field(None, alias="Data.Major Minerals.Magnesium")
    data_major_minerals_phosphorus: Optional[float] = Field(None, alias="Data.Major Minerals.Phosphorus")
    data_major_minerals_potassium: Optional[float] = Field(None, alias="Data.Major Minerals.Potassium")
    data_major_minerals_sodium: Optional[float] = Field(None, alias="Data.Major Minerals.Sodium")
    data_major_minerals_zinc: Optional[float] = Field(None, alias="Data.Major Minerals.Zinc")
    data_vitamins_vitamin_a_iu: Optional[float] = Field(None, alias="Data.Vitamins.Vitamin A - IU")
    data_vitamins_vitamin_a_rae: Optional[float] = Field(None, alias="Data.Vitamins.Vitamin A - RAE")
    data_vitamins_vitamin_b12: Optional[float] = Field(None, alias="Data.Vitamins.Vitamin B12")
    data_vitamins_vitamin_b6: Optional[float] = Field(None, alias="Data.Vitamins.Vitamin B6")
    data_vitamins_vitamin_c: Optional[float] = Field(None, alias="Data.Vitamins.Vitamin C")
    data_vitamins_vitamin_e: Optional[float] = Field(None, alias="Data.Vitamins.Vitamin E")
    data_vitamins_vitamin_k: Optional[float] = Field(None, alias="Data.Vitamins.Vitamin K")
